const countryList = {
  AED: "AE",
  AFN: "AF",
  XCD: "AG",
  ALL: "AL",
  AMD: "AM",
  ANG: "AN",
  AOA: "AO",
  AQD: "AQ",
  ARS: "AR",
  AUD: "AU",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  XOF: "BE",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  NOK: "BV",
  BWP: "BW",
  BYR: "BY",
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  XAF: "CF",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUP: "CU",
  CVE: "CV",
  CYP: "CY",
  CZK: "CZ",
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DZD: "DZ",
  ECS: "EC",
  EEK: "EE",
  EGP: "EG",
  ETB: "ET",
  EUR: "FR",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GGP: "GG",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LTL: "LT",
  LVL: "LV",
  LYD: "LY",
  MAD: "MA",
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRO: "MR",
  MTL: "MT",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  XPF: "NC",
  NGN: "NG",
  NIO: "NI",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SKK: "SK",
  SLL: "SL",
  SOS: "SO",
  SRD: "SR",
  STD: "ST",
  SVC: "SV",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  UYU: "UY",
  UZS: "UZ",
  VEF: "VE",
  VND: "VN",
  VUV: "VU",
  YER: "YE",
  ZAR: "ZA",
  ZMK: "ZM",
  ZWD: "ZW",
};

const countries = [
{ name: "Afghanistan", currency: "AFN", code: "AF" },
{ name: "Albania", currency: "ALL", code: "AL" },
{ name: "Algeria", currency: "DZD", code: "DZ" },
{ name: "Argentina", currency: "ARS", code: "AR" },
{ name: "Armenia", currency: "AMD", code: "AM" },
{ name: "Australia", currency: "AUD", code: "AU" },
{ name: "Austria", currency: "EUR", code: "AT" },
{ name: "Azerbaijan", currency: "AZN", code: "AZ" },
{ name: "Bahrain", currency: "BHD", code: "BH" },
{ name: "Bangladesh", currency: "BDT", code: "BD" },
{ name: "Belarus", currency: "BYN", code: "BY" },
{ name: "Belgium", currency: "EUR", code: "BE" },
{ name: "Belize", currency: "BZD", code: "BZ" },
{ name: "Benin", currency: "XOF", code: "BJ" },
{ name: "Bhutan", currency: "BTN", code: "BT" },
{ name: "Bolivia", currency: "BOB", code: "BO" },
{ name: "Bosnia and Herzegovina", currency: "BAM", code: "BA" },
{ name: "Botswana", currency: "BWP", code: "BW" },
{ name: "Brazil", currency: "BRL", code: "BR" },
{ name: "Brunei", currency: "BND", code: "BN" },
{ name: "Bulgaria", currency: "BGN", code: "BG" },
{ name: "Burkina Faso", currency: "XOF", code: "BF" },
{ name: "Burundi", currency: "BIF", code: "BI" },
{ name: "Cambodia", currency: "KHR", code: "KH" },
{ name: "Cameroon", currency: "XAF", code: "CM" },
{ name: "Canada", currency: "CAD", code: "CA" },
{ name: "Chile", currency: "CLP", code: "CL" },
{ name: "China", currency: "CNY", code: "CN" },
{ name: "Colombia", currency: "COP", code: "CO" },
{ name: "Costa Rica", currency: "CRC", code: "CR" },
{ name: "Croatia", currency: "EUR", code: "HR" },
{ name: "Cuba", currency: "CUP", code: "CU" },
{ name: "Cyprus", currency: "EUR", code: "CY" },
{ name: "Czech Republic", currency: "CZK", code: "CZ" },
{ name: "Denmark", currency: "DKK", code: "DK" },
{ name: "Dominican Republic", currency: "DOP", code: "DO" },
{ name: "Ecuador", currency: "USD", code: "EC" },
{ name: "Egypt", currency: "EGP", code: "EG" },
{ name: "El Salvador", currency: "USD", code: "SV" },
{ name: "Estonia", currency: "EUR", code: "EE" },
{ name: "Ethiopia", currency: "ETB", code: "ET" },
{ name: "Finland", currency: "EUR", code: "FI" },
{ name: "France", currency: "EUR", code: "FR" },
{ name: "Georgia", currency: "GEL", code: "GE" },
{ name: "Germany", currency: "EUR", code: "DE" },
{ name: "Ghana", currency: "GHS", code: "GH" },
{ name: "Greece", currency: "EUR", code: "GR" },
{ name: "Guatemala", currency: "GTQ", code: "GT" },
{ name: "Honduras", currency: "HNL", code: "HN" },
{ name: "Hong Kong", currency: "HKD", code: "HK" },
{ name: "Hungary", currency: "HUF", code: "HU" },
{ name: "Iceland", currency: "ISK", code: "IS" },
{ name: "India", currency: "INR", code: "IN" },
{ name: "Indonesia", currency: "IDR", code: "ID" },
{ name: "Iran", currency: "IRR", code: "IR" },
{ name: "Iraq", currency: "IQD", code: "IQ" },
{ name: "Ireland", currency: "EUR", code: "IE" },
{ name: "Israel", currency: "ILS", code: "IL" },
{ name: "Italy", currency: "EUR", code: "IT" },
{ name: "Jamaica", currency: "JMD", code: "JM" },
{ name: "Japan", currency: "JPY", code: "JP" },
{ name: "Jordan", currency: "JOD", code: "JO" },
{ name: "Kazakhstan", currency: "KZT", code: "KZ" },
{ name: "Kenya", currency: "KES", code: "KE" },
{ name: "Kuwait", currency: "KWD", code: "KW" },
{ name: "Kyrgyzstan", currency: "KGS", code: "KG" },
{ name: "Laos", currency: "LAK", code: "LA" },
{ name: "Latvia", currency: "EUR", code: "LV" },
{ name: "Lebanon", currency: "LBP", code: "LB" },
{ name: "Libya", currency: "LYD", code: "LY" },
{ name: "Lithuania", currency: "EUR", code: "LT" },
{ name: "Luxembourg", currency: "EUR", code: "LU" },
{ name: "Madagascar", currency: "MGA", code: "MG" },
{ name: "Malawi", currency: "MWK", code: "MW" },
{ name: "Malaysia", currency: "MYR", code: "MY" },
{ name: "Maldives", currency: "MVR", code: "MV" },
{ name: "Mali", currency: "XOF", code: "ML" },
{ name: "Malta", currency: "EUR", code: "MT" },
{ name: "Mauritania", currency: "MRU", code: "MR" },
{ name: "Mauritius", currency: "MUR", code: "MU" },
{ name: "Mexico", currency: "MXN", code: "MX" },
{ name: "Moldova", currency: "MDL", code: "MD" },
{ name: "Mongolia", currency: "MNT", code: "MN" },
{ name: "Montenegro", currency: "EUR", code: "ME" },
{ name: "Morocco", currency: "MAD", code: "MA" },
{ name: "Mozambique", currency: "MZN", code: "MZ" },
{ name: "Myanmar", currency: "MMK", code: "MM" },
{ name: "Namibia", currency: "NAD", code: "NA" },
{ name: "Nepal", currency: "NPR", code: "NP" },
{ name: "Netherlands", currency: "EUR", code: "NL" },
{ name: "New Zealand", currency: "NZD", code: "NZ" },
{ name: "Nicaragua", currency: "NIO", code: "NI" },
{ name: "Niger", currency: "XOF", code: "NE" },
{ name: "Nigeria", currency: "NGN", code: "NG" },
{ name: "North Korea", currency: "KPW", code: "KP" },
{ name: "Norway", currency: "NOK", code: "NO" },
{ name: "Oman", currency: "OMR", code: "OM" },
{ name: "Pakistan", currency: "PKR", code: "PK" },
{ name: "Panama", currency: "PAB", code: "PA" },
{ name: "Paraguay", currency: "PYG", code: "PY" },
{ name: "Peru", currency: "PEN", code: "PE" },
{ name: "Philippines", currency: "PHP", code: "PH" },
{ name: "Poland", currency: "PLN", code: "PL" },
{ name: "Portugal", currency: "EUR", code: "PT" },
{ name: "Qatar", currency: "QAR", code: "QA" },
{ name: "Romania", currency: "RON", code: "RO" },
{ name: "Russia", currency: "RUB", code: "RU" },
{ name: "Rwanda", currency: "RWF", code: "RW" },
{ name: "Saudi Arabia", currency: "SAR", code: "SA" },
{ name: "Senegal", currency: "XOF", code: "SN" },
{ name: "Serbia", currency: "RSD", code: "RS" },
{ name: "Singapore", currency: "SGD", code: "SG" },
{ name: "Slovakia", currency: "EUR", code: "SK" },
{ name: "Slovenia", currency: "EUR", code: "SI" },
{ name: "Somalia", currency: "SOS", code: "SO" },
{ name: "South Africa", currency: "ZAR", code: "ZA" },
{ name: "South Korea", currency: "KRW", code: "KR" },
{ name: "Spain", currency: "EUR", code: "ES" },
{ name: "Sri Lanka", currency: "LKR", code: "LK" },
{ name: "Sudan", currency: "SDG", code: "SD" },
{ name: "Sweden", currency: "SEK", code: "SE" },
{ name: "Switzerland", currency: "CHF", code: "CH" },
{ name: "Syria", currency: "SYP", code: "SY" },
{ name: "Taiwan", currency: "TWD", code: "TW" },
{ name: "Tajikistan", currency: "TJS", code: "TJ" },
{ name: "Tanzania", currency: "TZS", code: "TZ" },
{ name: "Thailand", currency: "THB", code: "TH" },
{ name: "Tunisia", currency: "TND", code: "TN" },
{ name: "Turkey", currency: "TRY", code: "TR" },
{ name: "Uganda", currency: "UGX", code: "UG" },
{ name: "Ukraine", currency: "UAH", code: "UA" },
{ name: "United Arab Emirates", currency: "AED", code: "AE" },
{ name: "United Kingdom", currency: "GBP", code: "GB" },
{ name: "United States", currency: "USD", code: "US" },
{ name: "Uruguay", currency: "UYU", code: "UY" },
{ name: "Uzbekistan", currency: "UZS", code: "UZ" },
{ name: "Venezuela", currency: "VES", code: "VE" },
{ name: "Vietnam", currency: "VND", code: "VN" },
{ name: "Yemen", currency: "YER", code: "YE" },
{ name: "Zambia", currency: "ZMW", code: "ZM" },
{ name: "Zimbabwe", currency: "ZWL", code: "ZW" }
];